name = "ragereplay"
account_id = "8fd10c75b5fa0ac0dad3a76f1c1cfb0c"
workers_dev = false
main = "src/index.ts"
compatibility_date = "2024-11-16"

route = { pattern = "api.ragereplay.com", custom_domain = true}
kv_namespaces = [
    { binding = "YOUTUBE_REQUESTS", id = "35b4ecc13bc649fa80f08ac30a43c5b9" },
    { binding = "GITHUB_DATA", id = "b3096dff62d64cd19877bcc6eac4676d" },
    { binding = "YOUTUBE_API_REQUESTS", id = "b2791e9b57e2450b830b79ab8c6f3cfe"}
]
observability.enabled = true