# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test Scraper

on:
  push:
    branches: [ master ]
    paths: 
      - "scraper/**"
  pull_request:
    branches: [ master ]
    paths: 
      - "scraper/**"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: cd scraper && npm ci
    - run: cd scraper && npm run build --if-present
    - run: cd scraper && npm test
