# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test API

on:
  push:
    branches: [ master ]
    paths:
      - "web/**"
  pull_request:
    branches: [ master ]
    paths:
      - "web/**"

jobs:
  build-web:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x, 23.x]
    
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm build
